### ISSUE TITLE
StudentForm/Avatar null

### ISSUE THREAD

**Issue by mrfour4** [quark1412/IT008_O14#16]
Khi avatar `null` sẽ gây lỗi `Unable to cast object of type 'System.DBNull' to type 'System.Byte[]'` trong file `StudentInfo.cs` 
![image](https://github.com/quark1412/IT008_O14/assets/95972670/66c5aadd-5e02-4c64-8d2f-fe2ab8273dbc)

**Comment by quark1412** [comment]
### Đã fix
Khi avt null sẽ load lên avt mặc định
![image](https://github.com/quark1412/IT008_O14/assets/40156711/7a4da7df-600e-4e94-81c5-eb5b08792ef3)
