### ISSUE TITLE
StudentForm/Không load lại môn sau khi hủy đăng kí

### ISSUE THREAD

**Issue by mrfour4** [quark1412/IT008_O14#18]
Khi đăng kí vài môn
![image](https://github.com/quark1412/IT008_O14/assets/95972670/b47b650b-c1c7-497f-b23b-9a0fbcd87ce5)
![image](https://github.com/quark1412/IT008_O14/assets/95972670/289f2a76-c76a-47bd-be7c-3e7e45dd01c1)

sau đó hủy đăng kí
![image](https://github.com/quark1412/IT008_O14/assets/95972670/8c6a1419-5ff6-4536-adb0-2ed10239b7b9)
![image](https://github.com/quark1412/IT008_O14/assets/95972670/007b699d-a241-41b7-9407-b8a973f47b48)

Khi quay lại dkhp thì không thể load lại các môn đã đăng kí dù đã bị hủy trước đó 
![image](https://github.com/quark1412/IT008_O14/assets/95972670/7241e37c-5d53-4a3f-97a5-429698cceef0)

**Comment by quark1412** [comment]
### Đã fix
Khi đăng ký
![image](https://github.com/quark1412/IT008_O14/assets/40156711/eb2e3e18-fe2d-44d8-a99b-f96d96bacffe)
Khi hủy
![image](https://github.com/quark1412/IT008_O14/assets/40156711/705dec79-5d96-41e1-9670-fb8f66c80bda)
Khi quay lại ĐKHP
![image](https://github.com/quark1412/IT008_O14/assets/40156711/78fbbb45-ab53-4613-840a-6c0253ca799d)
