### ISSUE TITLE
Form Teacher

### ISSUE THREAD

**Issue by mrfour4** [quark1412/IT008_O14#23]
# Thông tin

## Hiển thị sai thông tin ngày sinh

-   Ô ngày sinh nên hiển thị theo format `dd/MM/yyyy` không nên hiển thị thêm thời gian

![image-1](https://github.com/quark1412/IT008_O14/assets/95972670/29505313-08ac-42ce-ab58-ad5743efb925)

## Lỗi hiển thị khi không có avatar

-   Không có avatar nên để một `placeholder avatar`

![image-2](https://github.com/quark1412/IT008_O14/assets/95972670/8bc11491-f1a2-457d-a729-240a573a1a3b)

# Lịch dạy

## Chức năng lọc khó hiểu

-   Lọc nên để textbox để người dùng lọc theo `Mã môn học`, hoặc `Tên môn học`

![image-3](https://github.com/quark1412/IT008_O14/assets/95972670/a86bb0ce-5de7-4ce7-973f-0f1387cb420c)

# Điểm

## Không hiển thị lớp mặc định

-   Nên chọn một lớp để hiển thị mặc định thay vì để trống

![image-4](https://github.com/quark1412/IT008_O14/assets/95972670/8b5f8893-99ae-4ef2-aa13-70971d191dbf)

## Lỗi khi sinh viên chưa đủ cột điểm (null)

![image-5](https://github.com/quark1412/IT008_O14/assets/95972670/7f01c608-40a8-4898-be89-2cfb3daa856a)

## Không verify điểm khi nhập điểm

- Điểm chỉ được nhập từ trong khoảng [0, 10]

![image](https://github.com/quark1412/IT008_O14/assets/95972670/de70bfb7-918f-463c-a0df-34585d975fae)

# Thống kê

- Cần xử lý trường hợp sinh viên chưa đủ cột điểm (`null`)

**Comment by irisus1** [comment]
## fix lỗi ngày xinh và avatar
![image](https://github.com/quark1412/IT008_O14/assets/146847404/b3ecfd3e-cd0b-4dd9-964a-81ff92170115)


## fix lỗi tìm kiếm ( nhập vào mã hoặc tên lớp)
![image](https://github.com/quark1412/IT008_O14/assets/146847404/de34c4f6-2f34-4afa-bfd2-fd0b550cfcba)

## Hiển thị lớp mặc định
![image](https://github.com/quark1412/IT008_O14/assets/146847404/577dde45-3c3d-4de1-a718-5311c5015ec7)

##Hiển thị điểm lúc null
![image](https://github.com/quark1412/IT008_O14/assets/146847404/119bd1e0-5ab8-4559-b3a9-e297b6828cbc)

# UPDATE: đã fix thêm lỗi nhập điểm thuộc khoảng [0,10]
### còn TH có điểm và xóa điểm đi thành null thì chưa bt cách xử lí
