### ISSUE TITLE
Lỗi ĐKHP trùng môn 

### ISSUE THREAD

**Issue by quark1412** [quark1412/IT008_O14#30]
Đã có môn học nhưng vẫn đăng kí được => bị trùng môn 
![image](https://github.com/quark1412/IT008_O14/assets/40156711/d1573e16-03a2-4282-ab8a-04f01a7ee5c2)

![image](https://github.com/quark1412/IT008_O14/assets/40156711/126f510e-950c-453d-8e4c-3ac154891fce)

**Comment by mrfour4** [comment]
fix function `JoinRegisterCourse()`,  thêm điều kiện check đăng kí trùng môn học khác ngày học ví dụ IT003.O11 và IT003.O12

Sinh viên 21521601 đã đăng kí môn `IT003.O11` nên không thể đăng kí thêm môn `IT003.O13` 
![image](https://github.com/quark1412/IT008_O14/assets/95972670/153b010d-0376-43eb-91bb-b39fcd3bb68f)
![image](https://github.com/quark1412/IT008_O14/assets/95972670/c75c841b-d187-4b77-b315-03454c9b4037)


*Bản fix ở update db 5*
