### ISSUE TITLE
Lỗi: không xóa học phần đã đăng ký của sinh viên sau khi reject thành công ở admin

### ISSUE THREAD

**Issue by quark1412** [quark1412/IT008_O14#32]
### Sau khi reject học phần đã đăng kí của sinh viên
![image](https://github.com/quark1412/IT008_O14/assets/40156711/7d35d81c-5125-445b-b8fa-aadc1cb09a49)
### thì danh sách những học phần đã đăng kí của sinh viên không được cập nhật
![image](https://github.com/quark1412/IT008_O14/assets/40156711/8fde3f67-2036-403f-a145-7aafabc2c2ae)
![image](https://github.com/quark1412/IT008_O14/assets/40156711/ec1e3054-d16f-4379-bc32-373a0c180e41)
### nhưng thời khóa biểu thì đã được cập nhật
![image](https://github.com/quark1412/IT008_O14/assets/40156711/d82371b7-0120-4288-83e7-b1e882ff2800)

**Comment by mrfour4** [comment]
Fix bug sẽ ở branch `db/fix/**`

Thêm action khi reject môn nào sẽ xóa môn đó khỏi danh sách dkhp 

*Danh sách dkhp*
![image](https://github.com/quark1412/IT008_O14/assets/95972670/9611cbd6-4c43-43ba-93bb-e56b9f1cffa6)

*Reject môn `IT006.O14`*
![image](https://github.com/quark1412/IT008_O14/assets/95972670/ec43e0dd-aee4-4afc-8da5-7e965b27a1bd)

_Môn  `IT006.O14` bị xóa khỏi danh sách đăng kí học phần_
![image](https://github.com/quark1412/IT008_O14/assets/95972670/7f6369a8-fe1c-4a58-9e00-70a677aceafa)
