### ISSUE TITLE
Lỗi: không cập nhật được môn ĐKHP

### ISSUE THREAD

**Issue by quark1412** [quark1412/IT008_O14#33]
### Khi nhấn cập nhật sau khi sửa môn trong danh sách ĐKHP thì bị lỗi
![image](https://github.com/quark1412/IT008_O14/assets/40156711/2d3c4551-73d1-404a-a2df-f72a21b64b2b)
### (sửa startDate với endDate thành TIMESTAMP)

**Comment by mrfour4** [comment]
Đổi kiểu dữ liệu `courseStartDay`, `courseEndDay` thành `TIMESTAMP`

![image](https://github.com/quark1412/IT008_O14/assets/95972670/01e53f5f-47e4-440d-a61e-f561578481d1)
