### ISSUE TITLE
Lỗi: không load được ảnh khi đăng nhập

### ISSUE THREAD

**Issue by quark1412** [quark1412/IT008_O14#34]
### Khi đăng nhập vào tài khoản _gv1_ thì bị lỗi vì avt null
![image](https://github.com/quark1412/IT008_O14/assets/40156711/d8301e17-b6c5-440a-b6af-7a8c44319ca3)
![image](https://github.com/quark1412/IT008_O14/assets/40156711/cff47482-e88c-489e-93c5-53c3bd1aca80)

**Comment by irisus1** [comment]
## Lỗi do update avt mà chưa bỏ vào resource sẽ push lên cùng với code admin sau
