### ISSUE TITLE
form Sinh viên - tag Thông tin 

### ISSUE THREAD

**Issue by mrfour4** [quark1412/IT008_O14#4]
@quark1412 
## Thông tin hiển thị chưa đúng
**DB**
![image](https://github.com/quark1412/IT008_O14/assets/95972670/a3f7eb4d-2bee-498d-bb82-545510ddcf79)
**UI**
![image](https://github.com/quark1412/IT008_O14/assets/95972670/5aeb071e-e7e0-4811-983d-1a4b42644dce)

- Khi ngày sinh là `null` => UI nên hiển thị chuỗi rỗng
- Nếu Ảnh đại diện `null` => UI nên để placeholder avatar 

![image](https://github.com/quark1412/IT008_O14/assets/95972670/d524241b-14e1-4f6a-a1e2-9ec0396e1ff7)

_Placeholder avatar_

**Comment by quark1412** [comment]
![image](https://github.com/quark1412/IT008_O14/assets/40156711/950ba93e-4ebe-47a0-9bad-eaf39ff22469)
Đã fix
